// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: messages.sql

package sqlc

import (
	"context"
)

const storeMessage = `-- name: StoreMessage :one
INSERT INTO messages(chat_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id
`

type StoreMessageParams struct {
	ChatID   int64  `db:"chat_id" json:"chat_id"`
	SenderID int64  `db:"sender_id" json:"sender_id"`
	Content  string `db:"content" json:"content"`
}

func (q *Queries) StoreMessage(ctx context.Context, db DBTX, arg StoreMessageParams) (int64, error) {
	row := db.QueryRowContext(ctx, storeMessage, arg.ChatID, arg.SenderID, arg.Content)
	var id int64
	err := row.Scan(&id)
	return id, err
}
