// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID        uuid.UUID    `db:"id" json:"id"`
	UserID    int32        `db:"user_id" json:"user_id"`
	ExpiresAt time.Time    `db:"expires_at" json:"expires_at"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type User struct {
	ID        int32        `db:"id" json:"id"`
	FirstName string       `db:"first_name" json:"first_name"`
	LastName  string       `db:"last_name" json:"last_name"`
	Email     string       `db:"email" json:"email"`
	Password  string       `db:"password" json:"password"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}
