// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, id int32) (User, error)
	SearchUserByEmail(ctx context.Context, email string) ([]User, error)
	StoreSession(ctx context.Context, arg StoreSessionParams) error
	StoreUser(ctx context.Context, arg StoreUserParams) error
}

var _ Querier = (*Queries)(nil)
